//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.Integration.Owin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Integration.Owin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Autofac lifetime scope injector was not found while trying to add injected middleware type &apos;{0}&apos; to the pipeline. Make sure you use app.UseAutofacMiddleware()  to register the lifetime scope injector and middleware at the same time; or app.UseAutofacLifetimeScopeInjector() before registering injected middleware if separating the scope injector from injected middleware..
        /// </summary>
        internal static string LifetimeScopeInjectorNotFoundWhileRegisteringMiddleware {
            get {
                return ResourceManager.GetString("LifetimeScopeInjectorNotFoundWhileRegisteringMiddleware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Autofac lifetime scope was found while trying to invoke injected middleware type &apos;{0}&apos;. Make sure you use app.UseAutofacMiddleware()  to register the lifetime scope injector and middleware at the same time; or app.UseAutofacLifetimeScopeInjector() if separating the scope injector from injected middleware..
        /// </summary>
        internal static string LifetimeScopeNotFoundWhileInjectingMiddleware {
            get {
                return ResourceManager.GetString("LifetimeScopeNotFoundWhileInjectingMiddleware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The middleware type &apos;{0}&apos; was registered with the application using Autofac but that type was not able to be resolved from the lifetime scope. Check your container registrations to ensure that &apos;{0}&apos; is registered. See the inner exception for details on what failed during resolution..
        /// </summary>
        internal static string MiddlewareNotRegistered {
            get {
                return ResourceManager.GetString("MiddlewareNotRegistered", resourceCulture);
            }
        }
    }
}
